### ISSUE TITLE
MFS and Kubernetes – subvolumes problem

### ISSUE THREAD

**Issue by rafamiga** [moosefs/moosefs#339]
## Have you read through available documentation and open Github issues?

Yes

## Is this a BUG report, FEATURE request, or a QUESTION? Who is the indended audience?

BUG

## System information

Not really important I guess...

#### Your moosefs version and its origin (moosefs.com, packaged by distro, built from source, ...).

MooseFS 3.0.109-1
Ubuntu ppa.

#### Operating system (distribution) and kernel version.

Ubuntu 18.04.3 LTS bionic

#### Hardware / network configuration, and underlying filesystems on master, chunkservers, and clients.

XFS JBODs
1 Master server
1 Metalogger
14 Chunk servers w/mix of HDDs and SSDs

#### How much data is tracked by moosefs master (order of magnitude)?

Not important for this bug, really.

## Describe the problem you observed.

When setting up a Kubernetes cluster and a problem was encountered with subvolumes residing on MFS filesystem.

My goal is to create a one docker volume pointing to a directory structure on MFS with subvolumes mounted in the pods under /home/dev/java path. This is my setup [YML]:

```
apiVersion: apps/v1
kind: StatefulSet
[...]
spec:
[...]
  serviceName: zz-transcode-nv
[...]
    spec:
        volumeMounts:
        - mountPath: /home/dev/java/archive-01
          name: archive-01
          subPath: archive-01
[...]
      volumes:
      - hostPath:
          path: /mfs/k8s/zzzz/zz-transcode-nv
          type: ""
        name: archive-01
[...]
```

NOTE: Type: "" is configured by Rancher and it seems to work well with my k8s cluster.

When running this pod k8s reports:

CreateContainerConfigError: stat /mfs/k8s/zzzz/zz-transcode-nv: no such file or directory

Of course the path exists:

```
# stat /mfs/k8s/zzzz/zz-transcode-nv
  File: /mfs/k8s/zzzz/zz-transcode-nv
  Size: 1               Blocks: 1          IO Block: 65536  directory
Device: 7fh/127d        Inode: 4117        Links: 7
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-02-12 04:31:08.000000000 +0000
Modify: 2020-02-11 09:52:23.000000000 +0000
Change: 2020-02-11 09:52:23.000000000 +0000
 Birth: -
```

To get around this, I tried to mount each subdirectory in /mfs/k8s/zzzz/zz-transcode-nv as a separate volume and it does work, here's a snippet from spec file [different directory]:

```
    spec:
        volumeMounts:
        - mountPath: /home/dev/java/ingest-01
          name: ingest-01
[...]
      volumes:
      - hostPath:
          path: /mfs/k8s/zzzz/zz-transocde-nv/ingest-01
          type: ""
        name: ingest-01
```

Now, I've found this vulnerability fix which I believe is related to this issue [CVE-2017-1002101]:

https://kubernetes.io/blog/2018/04/04/fixing-subpath-volume-vulnerability/

This part of the above solution seems important:

Starting with the base volume, open each path segment one by one, using the openat() syscall, and disallow symlinks. With each path segment, validate that the current path is within the base volume.

And the reason I'm reporting this issue is a flawless NFS volumes subpath integration [root accessible, not rootsquash is used] . it's only when I point a volume to MFS-backed filesystem k8s starts to complain about a path being not found.

Other than this, k8s has no problem with MFS-backed volumes, it can create directories when instructed etc. – no permissions problems whatsoever.

Any ideas?

#### Can you reproduce it? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

This happens every time I create a volume with subpath on MFS.

**Comment by xandrus** [comment]
Hi,

This sounds really weird. There shouldn't be any problem with MooseFS and Kubernetes subPath.
Would you share with us your MooseFS operation log during pod build?
Just execute this command:
```
cat /mfs/.oplog | tee ~/moosefs-k8s-op.log
```
And when the operation is finished just press the ctrl+c key.

Also, I would like to add that I have made a fast test with mooseFS and K8S.
There ware two tests. The first one was with subfolder dir1 that exists on a MooseFS path.
```
# /moosefs/k8s/A/G/dir1
```
The second test was with missing dir1 subfolder on a MooseFS path.
```
# /moosefs/k8s/A/G/
``` 
In the second case subfolder, dir1 was created during pod build. 
In both cases, all goes OK without any problems and errors. I was able to list, create files and folders. All created content inside pod was available on the MooseFS.

Maybe I missed something in your pod configuration.
This is what I have made:

**K8S version: v1.17.2**
**MooseFS version: 3.0.110**

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: local-test
spec:
  containers:
  - name: test-container
    image: k8s.gcr.io/busybox
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "ls -al /mnt/mfs-vol/dir1 && sleep 10000"
    volumeMounts:
    - name: mfs-vol
      mountPath: /mnt/mfs-vol/dir1
      subPath: dir1
  volumes:
  - name: mfs-vol
    hostPath:
      # MooseFS mounted on /moosefs path
      path: /moosefs/k8s/A/G
      type: Directory
```

I'm looking forward to hearing from you.
