### ISSUE TITLE
Regarding whether MooseFS 3.0.118 can be directly upgraded to 4.56.5?

### ISSUE THREAD

**Issue by Leif160519** [moosefs/moosefs#591]
## Have you read through available documentation, open Github issues and Github Q&A Discussions?

Yes/No

#### Your moosefs version and its origin (moosefs.com, packaged by distro, built from source, ...).
|env|master ip|version|
|-|-|-|
|prod|192.168.31.110|3.0.118|
|test|192.168.31.120|4.56.5|
#### Operating system (distribution) and kernel version.
|env|master ip|os|kernel|
|-|-|-|-|
|prod|192.168.31.110|ubuntu20.04|5.4.0-193-generic|
|test|192.168.31.120|ubuntu 22.04|5.15.0-119-generic|
#### Hardware / network configuration, and underlying filesystems on master, chunkservers, and clients.
8c 16g 1000mbps 
#### How much data is tracked by moosefs master (order of magnitude)?
< 250G
 - All fs objects:
 - Total space:
 - Free space:
 - RAM used:
 - last metadata save duration:

## Describe the problem you observed.

I have compiled and set up a new version of MooseFS cluster in the testing environment, which is 4.56.5. Personally, I also have a formal environment running MooseFS 3.0.118. I want to know if this 3.0.118 version can be directly upgraded to 4.56.5 by replacing the binary files and restarting the service. Additionally, I have a Kubernetes cluster that uses MooseFS 3.0.118 as its storage class. If it's possible to upgrade to version 4.56.5, will there be any impact on the Kubernetes cluster?

**Comment by Leif160519** [comment]
After compiling, I found that the executable file 'mfstools' was not generated, which means commands like 'mfsgetquota' and 'mfsgetsclass' cannot be used. The lower version of moosefs-client will also prompt 'not MFS object'. Do I need to wait for the official installation package to be released for support? Currently, https://repository.moosefs.com/moosefs-4/ is forbidden.
![image](https://github.com/user-attachments/assets/971ffd06-32d5-4bfb-9a32-29419267a6fb)

**Comment by Leif160519** [comment]
> The new version does not have a `mfstools` executable anymore, the tools are now separate. Did you use the `linux_build.sh` script? Check out all the binaries that have been created in the `mfsclient` subdirectory, there is `mfsquota`, `mfssclass` and many more. If you run the install command `make install` as root, they all become available in your system. If not, you can use them directly via their path for testing purposes. The only difference is that after installing, aliases like `mfsgetquota` will become available, as long as you are just using binaries from the `msfclient` directory, you need to use the commands like `mfsquota get`, `mfsquota set` etc.
> 
> We are happy you like the new GUI :) And we are working on getting the package repository up and running.
> 
> Yes, you should be able to upgrade 3.0.118 directly to 4.56.5. As always, remember to back up your metadata, just in case. After you stop your old master, copy the `metadata.mfs` and all the` changelog.*.mfs` files to a backup location, then start the new master and it should load all your metadata without any problems.
> 
> Regarding Kubernetes: the driver for the MooseFS 3 version will not work with the client from MooseFS 4. You can upgrade your CGI, master, chunk servers and metaloggers, but you need to keep the old mount and tools for now to work with Kubernetes. You can install the new mount on another machine, just to have regular access to the filesystem. And as long as you connect a version 3 client, you definitely should not use the EC format for your chunks. We are working on a driver that will be compatible with MooseFS 4, it shouldn't take long now.

Thank you very much for your reply. Today, I found that the apt source of MooseFS-4 can be updated and installed, and I successfully upgraded it to version 4.56.6. However, I noticed that there is also a new version of MooseFS-CSI-Plugin. Could you please advise me which image I should use instead?
```
curl -X GET https://registry.moosefs.com/v2/moosefs-csi-plugin/tags/list | jq


{
  "name": "moosefs-csi-plugin",
  "tags": [
    "latest",
    "0.9.6-dev",
    "0.9.4-dev",
    "dev",
    "0.9.2-4.42.0-pro",
    "latest-dev",
    "0.9.4-3.0.117",
    "0.9.2-4.32.0-pro",
    "0.9.2-4.36.4-pro",
    "0.9.6-3.0.117",
    "0.9.2-dev",
    "0.9.6-4.49.0-pro",
    "0.9.4-3.0.117-pro",
    "0.9.6-3.0.117-pro",
    "0.9.1",
    "0.9.7-3.0.118-pro",
    "0.9.2-3.0.115",
    "0.9.2-4.38.4-pro",
    "0.9.5-dev",
    "0.9.6-3.0.118",
    "0.9.4-4.44.4-pro",
    "0.9.2-4.30.2",
    "0.9.2-3.0.116",
    "0.9.2-3.0.116-pro",
    "0.9.2-4.37.5-pro",
    "0.9.7-4.56.3-pro"
  ]
}
```
@chogata

**Comment by xandrus** [comment]
Hi @Leif160519

Can you try this driver with some fixes that I made recently?
https://github.com/xandrus/moosefs-csi/tree/dev

I would also like to add that the CSI image with the MooseFS 4.56.6 CE client is publicly available on ghrc:
https://github.com/users/xandrus/packages/container/package/moosefs-csi

If everything works flawlessly, I will try to push these changes to the main moosefs-csi repository.

**Comment by Leif160519** [comment]
> 你好@Leif160519
> 
> 您可以尝试使用我最近修复的一些问题来测试这个驱动程序吗？ https://github.com/xandrus/moosefs-csi/tree/dev
> 
> 我还想补充一点，带有 MooseFS 4.56.6 CE 客户端的 CSI 映像在 ghrc 上公开可用： [https ://github.com/users/xandrus/packages/container/package/moosefs-csi](https://github.com/users/xandrus/packages/container/package/moosefs-csi)
> 
> 如果一切顺利，我将尝试将这些更改推送到主 moosefs-csi 存储库。

I want to know the meaning of mfs_mount_options. My MFS doesn't have a password set, so how should I fill in this parameter? I deployed it as is, but the result is in a not-ready state.
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: csi-moosefs-config
data:
  # MooseFS master hostname or IP
  master_host: "192.168.31.110"
  # MooseFS master port
  master_port: "9421"
  # MooseFS root directory for all claims within this Kubernetes cluster
  k8s_root_dir: "/@peanut/kubernetes/k3s/dev"
  # MooseFS directory (relative to csi_root_dir) for all driver data
  # (effective working dir will be calculated as k8s_root_dir/driver_working_dir)
  driver_working_dir: "pv_data"
  # Number of pre-created MooseFS mounts on each node
  mount_count: "1"
  # Should driver log to k8s_root_dir/driver_working_dir/logs directory
  mfs_logging: "true"
  # Additional mfsmount options
  mfs_mount_options: "mfsmd5pass=[MD5 hash]"
```

```
kubectl logs -f -n kube-system csi-moosefs-node-8b25g -c csi-moosefs-plugin
time="2024-10-10T08:12:33Z" level=info msg="Starting new service (mode: node; master-host: 192.168.31.110; master-port: 9421; mfs-mount-options mfsmd5pass=[MD5 hash]; node-id: k3s-master-01; root-dir: /@peanut/kubernetes/k3s/dev; plugin-data-dir: pv_data)"
time="2024-10-10T08:12:33Z" level=info msg="NewNodeService creation (mfsmaster 192.168.31.110, rootDir /@peanut/kubernetes/k3s/dev, pluginDataDir pv_data, nodeId k3s-master-01, mountPointsCount 1)"
time="2024-10-10T08:12:33Z" level=info msg="MountMfs - source: 192.168.31.110:9421:/@peanut/kubernetes/k3s/dev, target: /mnt/k3s-master-01, options: [mfsmd5pass=[MD5 hash]]"
time="2024-10-10T08:12:33Z" level=error msg="main - couldn't create node service. Error: Mounter::Mount -- mounting failed: exit status 1 cmd: 'mount -t moosefs -o mfsmd5pass=[MD5 hash] 192.168.31.110:9421:/@peanut/kubernetes/k3s/dev /mnt/k3s-master-01' output: \"bad md5 definition (md5 should be given as 32 hex digits)\\n\""
```
